spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myblogsystem?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.lrm: info
  file: log/blog-pro.log

server:
  port: 8081

